language: cpp
compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  matrix:
#    - export NODE_VERSION="0.10"
#    - export NODE_VERSION="0.12"
#    - export NODE_VERSION="iojs-v1.0"
#    - export NODE_VERSION="iojs-v1"
#    - export NODE_VERSION="iojs-v2"
#    - export NODE_VERSION="iojs-v3"
#    - export NODE_VERSION="4"
    - export NODE_VERSION="5"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - git -C .nvm checkout "$(git -C .nvm describe --tags `git -C .nvm rev-list --tags --max-count=1`)"
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION == "4" ]; then
      npm run-script coverage;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
