language: node_js
compiler:
  - gcc
node_js:
  - "0.10"
  - "0.11"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - sudo g++ --version;
  - sudo apt-get update -qq;

  - git submodule update --init --recursive
after_success:
  - npm run-script coverage
cache:
  directories:
    - node_modules
