language: node_js

compiler: gcc
sudo: false

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

jobs:
  include:
    - stage: test
      node_js: "node"
      os: linux
      before_script: npm run lint || exit 1;
      after_success: npm run-script coverage;
    - stage: platform-test
      node_js: "node"
      os: osx    
    - stage: platform-test
      node_js: "7"
      os: linux
    - stage: platform-test
      node_js: "7"
      os: osx
    - stage: platform-test
      node_js: "lts/boron"
      os: linux
    - stage: platform-test
      node_js: "lts/boron"
      os: osx
    - stage: platform-test
      node_js: "lts/argon"
      os: linux
    - stage: platform-test
      node_js: "lts/argon"
      os: osx
    - stage: platform-test
      node_js: "0.12"
      os: linux
    - stage: platform-test
      node_js: "0.10"
      os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
