language: node_js

compiler: gcc

jobs:
  include:
    - stage: lint
      node_js: "12"
      os: linux
      install: npm install --ignore-scripts
      script: npm run lint || exit 1;

    - stage: test
      node_js: "13"
      os: linux
    - stage: test
      node_js: "13"
      os: osx
    - stage: test
      node_js: "12"
      os: linux
      after_success: npm run-script coverage;
    - stage: test
      node_js: "12"
      os: osx
    - stage: test
      node_js: "10"
      os: linux
    - stage: test
      node_js: "10"
      os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-6
      - g++-6

before_install:
  - echo $TRAVIS_NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      if [[ $(node -v) =~ v1[23] ]]; then
        export CC="gcc-6";
        export CXX="g++-6";
        export LINK="gcc-6";
        export LINKXX="g++-6";
      else
        export CC="gcc-4.9";
        export CXX="g++-4.9";
        export LINK="gcc-4.9";
        export LINKXX="g++-4.9";
      fi
    fi
  - nvm --version
  - node --version
  - npm --version
  - ${CC:-gcc} --version
  - ${CXX:-g++} --version

install:
  - npm install

script:
  - npm run build --force
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
