language: node_js
node_js:
  - "7"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

sudo: required

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

matrix:
  fast_finish: true
  exclude:
    - node_js: iojs
    - node_js: "0.10"
      os: osx
    - node_js: "0.12"
      os: osx

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
      export DOCKER_COPY="/tmp/alpine";
      cp -r $TRAVIS_BUILD_DIR $DOCKER_COPY;
      docker pull mhart/alpine-node:$TRAVIS_NODE_VERSION;
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run lint || exit 1;
    fi
  - npm test
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      docker run --rm -i --env SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true -v $DOCKER_COPY:/tmp/node-sass -w /tmp/node-sass mhart/alpine-node:$TRAVIS_NODE_VERSION /bin/sh -c "apk add --no-cache python=2.7.12-r0 make gcc g++ && npm install --unsafe-perm && npm test";
    fi

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $TRAVIS_NODE_VERSION == "4" ]; then
      npm run-script coverage;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
