language: node_js

env: SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

compiler: gcc

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1.0"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"

matrix:
  fast_finish: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.7 g++-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 20
  - g++ --version
  - sudo apt-get update -qq
  - git submodule update --init --recursive

after_success: npm run-script coverage

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
