language: cpp
compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
  matrix:
    - export NODE_VERSION="11"
    - export NODE_VERSION="10"
    - export NODE_VERSION="9"
    - export NODE_VERSION="8"
    - export NODE_VERSION="7"
    - export NODE_VERSION="6"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - git -C .nvm checkout "$(git -C .nvm describe --tags `git -C .nvm rev-list --tags --max-count=1`)"
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.9";
      export CXX="g++-4.9";
      export LINK="gcc-4.9";
      export LINKXX="g++-4.9";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION == "4" ]; then
      npm run-script coverage;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

before_deploy:
  - export RELEASE_BINDING_FILE=$(node scripts/travis-release.js)

deploy:
  provider: releases
  skip_cleanup: true
  file: "${RELEASE_BINDING_FILE}"
  api_key:
    secure: GaM0z8pPpodKkBagFLQzGMzUJOl6Zj0kmhhk7FwPN4vrbCNnb9mtn9AVF/d3rTCS1yhMJ7urbR9yoC9GyYcmE6NGoIzvoT4Iha919a+/3J6cHpM0DVLfXErj1zAZSBImdhSxvnbMxSr07wAn15Dvmv1bJv+JLNE0oB51bPGEtbq9FV6An08qHOOjsPAVhi0rt/zrhtrm0MTFEWML2Kkf3rpeyqyP8RiJZkzmtJUWw/8aMmws8XOwX7TlrH/hpotHIoTSrbmcYryC+YEFbbvVXYvKBGaKFCx0xcLinG/clFqJPbS96g1JUW4ZUf96lHXxKInnkw37ujrnn7s2kjSZoRJsxqigoW8H/kwtOPzHsKHwN720bB9SHR2m6pdnfZeEx2Oc2OCqRXM430C/uH4g04t8uibZU78UVS8xgK43cFh9TZy0TYBe0Wn4/l1Tku06Xs7pyHYnigfE0ch4exL/NMsmBw/ALfkRmoR6lFuPDab3kN+4uO+VOmbYNbLlCf4wRAJNi/mMR+iw/Zv8BO9keR0UTR5cbNDo8KIjJZLo0F8rw1rY34WMgYDh52qa3q18gM41t1E625yJ5Zm6lk+wdTFrOJOjiD3zbSVfXWd2OzyCwY9D7kxTyBS+GQDh9GlTwBm/3mudkKp1xFmcoe476jFwP7XovccEbRgslv1hYtY=
  on:
    tags: true
    repo: bigcommerce-labs/node-sass
