version: "{build}"

build: off

environment:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
  matrix:
    # node.js
    - nodejs_version: 0.10
    - nodejs_version: 0    # will fetch the latest node.js version
    # io.js
    - nodejs_version: 1    # will fetch the latest io.js version

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - git submodule update --init --recursive
  - ps: npm install --msvs_version=2013

test_script: npm test
