name: Build bindings for Alpine releases

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 14
          - 15
          - 16

        include:
          - node: 12
            python: python2
          - node: 14
            python: python3
          - node: 15
            python: python3
          - node: 16
            python: python3

    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache ${{ matrix.python }} make git gcc g++

      - uses: actions/checkout@v2

      - name: Install packages
        run: npm install --unsafe-perm
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v2
        if: github.repository_owner == 'sass' && github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}
          path: vendor/
